package gadget.util
{
	public class InputFormUtils
	{
		public static function getInputForms():Array {
			return [
				{id:1, name:'Combined Input Form'}
			];
		}
		
		public static function getInputFormFields():Array {
			return [
				{page:0, col:0, title:"Key Data"},
				{page:0, col:0, header:"Household"},
				{page:0, col:0, entity:"Account", element_name:"AccountName"},
				{page:0, col:0, entity:"Account", element_name:"Location"},
				{page:0, col:0, entity:"Account", element_name:"AccountType"},
				{page:0, col:0, entity:"Account", element_name:"CustomText35"},
				{page:0, col:0, entity:"Account", element_name:"CustomPickList0"},
				{page:0, col:0, entity:"Account", element_name:"CustomText30"},
				{page:0, col:0, entity:"Account", element_name:"CustomText31"},
				{page:0, col:0, entity:"Account", element_name:"CustomText33"},
				{page:0, col:0, entity:"Account", element_name:"PrimaryBillToCity"},
				{page:0, col:0, entity:"Account", element_name:"MainPhone"},
				{page:0, col:0, entity:"Account", element_name:"MainFax"},
				{page:0, col:0, header:"Consumer"},
				{page:0, col:0, entity:"Contact", element_name:"CustomPickList26"},
				{page:0, col:0, entity:"Contact", element_name:"MrMrs"},
				{page:0, col:0, entity:"Contact", element_name:"Gender"},
				{page:0, col:0, entity:"Contact", element_name:"ContactFirstName"},
				{page:0, col:0, entity:"Contact", element_name:"ContactLastName"},
				{page:0, col:0, entity:"Contact", element_name:"CellularPhone"},
				{page:0, col:0, entity:"Contact", element_name:"WorkPhone"},
				{page:0, col:0, entity:"Contact", element_name:"ContactEmail"},
				{page:0, col:0, entity:"Contact", element_name:"BestTimeToCall"},
				{page:0, col:1, header:"Consumer Contact"},
				{page:0, col:1, entity:"Service Request", element_name:"Product"},
				{page:0, col:1, entity:"Service Request", element_name:"CustomText61"},
				{page:0, col:1, entity:"Service Request", element_name:"Source"},
				{page:0, col:1, entity:"Service Request", element_name:"IndexedPick2"},
				{page:0, col:1, entity:"Service Request", element_name:"CustomDate26"},
				{page:0, col:1, entity:"Service Request", element_name:"CustomDate29"},
				{page:0, col:1, entity:"Service Request", element_name:"Subject"},
				{page:0, col:1, entity:"Service Request", element_name:"Description"},
				{page:0, col:1, entity:"Service Request", element_name:"IndexedPick3"},
				{page:0, col:1, entity:"Service Request", element_name:"IndexedPick4"},
				{page:0, col:1, entity:"Service Request", element_name:"IndexedPick5"},
				{page:0, col:1, entity:"Service Request", element_name:"IndexedPick1"},
				{page:0, col:1, entity:"Service Request", element_name:"CustomPickList3"},
				{page:0, col:1, entity:"Service Request", element_name:"CustomPickList4"},
				{page:0, col:1, entity:"Service Request", element_name:"Owner"},
				{page:0, col:1, entity:"Service Request", element_name:"ReassignOwnerFlag"},
				{page:0, col:1, entity:"Service Request", element_name:"Status"},
				{page:0, col:1, entity:"Service Request", element_name:"Priority"},
				{page:1, col:0, title:"Household Details"},
				{page:1, col:0, header:"Household Details"},
				{page:1, col:0, entity:"Account", element_name:"NumberEmployees"},
				{page:1, col:0, entity:"Account", element_name:"CustomNumber0"},
				{page:1, col:0, entity:"Account", element_name:"Owner"},
				{page:1, col:0, entity:"Account", element_name:"ExternalSystemId"},
				{page:1, col:1, entity:"Account", element_name:"CustomText36"},
				{page:1, col:1, entity:"Account", element_name:"CustomDate25"},
				{page:1, col:1, entity:"Account", element_name:"CustomNumber1"},
				{page:1, col:1, entity:"Account", element_name:"CustomText37"},
				{page:1, col:1, entity:"Account", element_name:"CustomDate26"},
				{page:1, col:1, entity:"Account", element_name:"CustomText38"},
				{page:1, col:1, entity:"Account", element_name:"CustomDate27"},
				{page:2, col:0, title:"Consumer Details"},
				{page:2, col:0, header:"Consumer Details"},
				{page:2, col:0, entity:"Contact", element_name:"ContactType"},
				{page:2, col:0, entity:"Contact", element_name:"CustomText53"},
				{page:2, col:0, entity:"Contact", element_name:"CustomPickList27"},
				{page:2, col:0, entity:"Contact", element_name:"DateofBirth"},
				{page:2, col:0, entity:"Contact", element_name:"Age"},
				{page:2, col:0, entity:"Contact", element_name:"IndexedPick1"},
				{page:2, col:0, entity:"Contact", element_name:"IndexedPick3"},
				{page:2, col:0, entity:"Contact", element_name:"CustomPickList29"},
				{page:2, col:0, entity:"Contact", element_name:"CustomPickList33"},
				{page:2, col:0, entity:"Contact", element_name:"CustomText30"},
				
				
				{page:2, col:1, header:"Opt-in"},
				{page:2, col:1, entity:"Contact", element_name:"CustomBoolean15"},
				{page:2, col:1, entity:"Contact", element_name:"CustomDate35"},
				{page:2, col:1, entity:"Contact", element_name:"CustomPickList32"},
				{page:2, col:1, entity:"Contact", element_name:"OptIn"},
				{page:2, col:1, entity:"Contact", element_name:"CustomDate36"},
				{page:2, col:1, entity:"Contact", element_name:"CustomPickList30"},
				{page:2, col:1, entity:"Contact", element_name:"CustomBoolean16"},
				{page:2, col:1, entity:"Contact", element_name:"CustomDate37"},
				{page:2, col:1, entity:"Contact", element_name:"CustomPickList31"},
				{page:2, col:1, entity:"Contact", element_name:"CustomPickList28"},				
				
				
				{page:3, col:0, title:"Contact Details"},
				{page:3, col:0, header:"Contact Details"},
				{page:3, col:0, entity:"Service Request", element_name:"SRNumber"},
				{page:3, col:0, entity:"Service Request", element_name:"CustomNumber1"},
				{page:3, col:0, entity:"Service Request", element_name:"CustomPickList1"},
				{page:3, col:0, entity:"Service Request", element_name:"IndexedShortText1"},
				{page:3, col:0, entity:"Service Request", element_name:"CustomDate27"},
				{page:3, col:0, entity:"Service Request", element_name:"CreatedDate"},
				{page:3, col:0, entity:"Service Request", element_name:"CustomText30"},
				{page:3, col:0, entity:"Service Request", element_name:"CustomDate25"},
				{page:3, col:0, entity:"Service Request", element_name:"CustomText34"},
				{page:3, col:0, entity:"Service Request", element_name:"CustomPickList11"},
				{page:3, col:0, entity:"Service Request", element_name:"CustomBoolean0"},
				{page:3, col:0, entity:"Service Request", element_name:"CustomDate28"},
				{page:3, col:1, entity:"Service Request", element_name:"CustomPickList5"},
				{page:3, col:1, entity:"Service Request", element_name:"CustomPickList7"},
				{page:3, col:1, entity:"Service Request", element_name:"CustomPickList8"},
				{page:3, col:1, entity:"Service Request", element_name:"CustomPickList6"},
				{page:3, col:1, entity:"Service Request", element_name:"CustomPickList9"},
				{page:3, col:1, entity:"Service Request", element_name:"CustomPickList10"},
				{page:3, col:1, entity:"Service Request", element_name:"CustomPickList0"},
				{page:3, col:1, entity:"Service Request", element_name:"CustomText42"},
				
				{page:4, col:0, title:"Questionnairs"},
				{page:4, col:0, header:"Questionnairs"},
				{page:4, col:0, link:"Survey URL", linkText:"Click here to take a quick survey", linkURL: "http://www.clicktools.com/survey?iv=3a129ab895da76f"},
				{page:4, col:1, link:"Feedback Link", linkText:"Click here for a feedback survey", linkURL: "http://www.clicktools.com/survey?iv=3b129b067e0cb75"},
				{page:4, col:1, entity:"Service Request", element_name:"CustomText1"},
				{page:4, col:1, entity:"Service Request", element_name:"IndexedLongText0"}
			];


		}
	}
}